### Prueba de coneccion
GET http://localhost:3000/

### Todas las Tiendas
GET http://localhost:3000/store
### Todas las Tiendas
GET http://localhost:3000/store/Australia


### Buscar en inventario por palabra en title de film y country de store
GET http://localhost:3000/store/Canada/inventory/film?name_film=club
### Buscar en inventario por nombre de actor que actua en pelicula y country de store
GET http://localhost:3000/store/Canada/inventory/film?name_actor=PENELOPE
### Buscar en inventario peliculas y country de store
GET http://localhost:3000/store/Canada/inventory/film

### Buscar en inventario peliculas y country de store
GET http://localhost:3000/store/Canada/inventory/film/new
### Buscar en inventario peliculas y country de store
GET http://localhost:3000/store/Canada/inventory/film/category/Horror


### Buscar en inventario por palabra en title de pelicula y id de store
//GET http://localhost:3000/store/1/inventory/film?name_film=club
### Buscar en inventario por nombre de actor que actua en pelicula y id de store
//GET http://localhost:3000/store/Canada/inventory/film?name_actor=PENELOPE
### Buscar en inventario peliculas y id de store
//GET http://localhost:3000/store/Canada/inventory/film


### Sacar Customer de una Store por Id
GET http://localhost:3000/store/1/custumer/2

### Editar una Customer de una Store por Id
PUT http://localhost:3000/store/1/custumer/2
Content-Type: application/json

{
    "address": "898 Lamnda Avenue"
}

### Crear un customer en un Store
POST http://localhost:3000/store/1/customer
Content-Type: application/json

{
    "store_id":"1",
    "first_name": "GEL",
    "last_name":"PEPE", 
    "adress_id": "603",   
    "active": "0",
    "create_date": "2021-09-25 22:32:31",
    "last_update": "2021-09-25 22:32:31"
}
###
POST http://localhost:3000/store/1/address
Content-Type: application/json

{
    "address":"225 AV Lupoez",
    "address2":"",
    "district":"QLSD",
    "city_id":"300",
    "postal_code":"1010",
    "phone":"25648756",
    "last_update":"2021-09-25 22:32:31",
    "location":[
        {
            "x": "153.1913094",
            "y": "-27.6333373"
        }
    ]
}



### Crear un rental en un Store
POST http://localhost:3000/store/1/customer/1/rental
Content-Type: application/json

{
    "rental_date":"2021-09-25 22:32:31",
    "inventory_id":"1",
    "return_date":"2021-09-25 22:32:31",
    "staff_id": "2",    
    "last_update":"2021-09-25 22:32:31"
}

### Crear un rental en un Store
POST http://localhost:3000/store/1/customer/1/rental
Content-Type: application/json

{
    "staff_id": "2", 
    "rental_id":"600",
    "amount":"1",
    "payment_date":"2021-09-25 22:32:31",       
    "last_update":"2021-09-25 22:32:31"
}


### GET Citys de una store por country
GET http://localhost:3000/store/Canada/city

### GET Citys de una store por country
GET http://localhost:3000/address




